name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Install Ruff
      run: pipx install ruff
        
    - name: Lint with Ruff
      run: ruff check --output-format=github --target-version=py311
      
    - name: Check formatting with Ruff
      run: ruff format --diff --target-version=py311
      continue-on-error: true
        
    - name: Run tests with coverage
      run: |
        mkdir -p junit
        pytest --junitxml=junit/test-results.xml \
              --cov=ai_architect_planner \
              --cov-report=xml \
              --cov-report=html \
              --cov-report=term
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          junit/test-results.xml
          coverage.xml
          htmlcov/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
